#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ibus
Version  : 1.5.24
Release  : 35
URL      : https://github.com/ibus/ibus/releases/download/1.5.24/ibus-1.5.24.tar.gz
Source0  : https://github.com/ibus/ibus/releases/download/1.5.24/ibus-1.5.24.tar.gz
Summary  : IBus Library
Group    : Development/Tools
License  : ICU LGPL-2.1
Requires: ibus-bin = %{version}-%{release}
Requires: ibus-data = %{version}-%{release}
Requires: ibus-lib = %{version}-%{release}
Requires: ibus-libexec = %{version}-%{release}
Requires: ibus-license = %{version}-%{release}
Requires: ibus-locales = %{version}-%{release}
Requires: ibus-man = %{version}-%{release}
Requires: ibus-python = %{version}-%{release}
Requires: ibus-python3 = %{version}-%{release}
Requires: UCD
Requires: glibc-locale
BuildRequires : UCD
BuildRequires : buildreq-gnome
BuildRequires : buildreq-kde
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : glibc-locale
BuildRequires : gobject-introspection
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : gtk3-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(dbus-python)
BuildRequires : pkgconfig(dconf)
BuildRequires : pkgconfig(gdk-wayland-3.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gobject-introspection-1.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(iso-codes)
BuildRequires : pkgconfig(pygobject-3.0)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(xkeyboard-config)
BuildRequires : pkgconfig(xtst)
BuildRequires : python3-core
BuildRequires : vala
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
IBus - Input Bus
Introduction
===
IBus is an Intelligent Input Bus. It is a new input framework for Linux OS.
It provides full featured and user friendly input method user interface.
It also may help developers to develop input method easily.

%package bin
Summary: bin components for the ibus package.
Group: Binaries
Requires: ibus-data = %{version}-%{release}
Requires: ibus-libexec = %{version}-%{release}
Requires: ibus-license = %{version}-%{release}

%description bin
bin components for the ibus package.


%package data
Summary: data components for the ibus package.
Group: Data

%description data
data components for the ibus package.


%package dev
Summary: dev components for the ibus package.
Group: Development
Requires: ibus-lib = %{version}-%{release}
Requires: ibus-bin = %{version}-%{release}
Requires: ibus-data = %{version}-%{release}
Provides: ibus-devel = %{version}-%{release}
Requires: ibus = %{version}-%{release}

%description dev
dev components for the ibus package.


%package doc
Summary: doc components for the ibus package.
Group: Documentation
Requires: ibus-man = %{version}-%{release}

%description doc
doc components for the ibus package.


%package lib
Summary: lib components for the ibus package.
Group: Libraries
Requires: ibus-data = %{version}-%{release}
Requires: ibus-libexec = %{version}-%{release}
Requires: ibus-license = %{version}-%{release}

%description lib
lib components for the ibus package.


%package libexec
Summary: libexec components for the ibus package.
Group: Default
Requires: ibus-license = %{version}-%{release}

%description libexec
libexec components for the ibus package.


%package license
Summary: license components for the ibus package.
Group: Default

%description license
license components for the ibus package.


%package locales
Summary: locales components for the ibus package.
Group: Default

%description locales
locales components for the ibus package.


%package man
Summary: man components for the ibus package.
Group: Default

%description man
man components for the ibus package.


%package python
Summary: python components for the ibus package.
Group: Default
Requires: ibus-python3 = %{version}-%{release}

%description python
python components for the ibus package.


%package python3
Summary: python3 components for the ibus package.
Group: Default
Requires: python3-core

%description python3
python3 components for the ibus package.


%prep
%setup -q -n ibus-1.5.24
cd %{_builddir}/ibus-1.5.24

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1615353538
unset LD_AS_NEEDED
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static --disable-python-library \
--disable-tests \
--sysconfdir=/usr/share/defaults \
--enable-wayland \
--disable-python2 \
--enable-gtk2 \
--enable-gtk3 \
--enable-xim \
--enable-surrounding-text \
--with-python=/usr/bin/python3 \
--enable-wayland \
--enable-introspection \
--disable-emoji-dict
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1615353538
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ibus
cp %{_builddir}/ibus-1.5.24/COPYING %{buildroot}/usr/share/package-licenses/ibus/caeb68c46fa36651acf592771d09de7937926bb3
cp %{_builddir}/ibus-1.5.24/COPYING.unicode %{buildroot}/usr/share/package-licenses/ibus/8f3995295bed2abde3107e544c985096cb9c745a
%make_install
%find_lang ibus10

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ibus
/usr/bin/ibus-daemon
/usr/bin/ibus-setup

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/IBus-1.0.typelib
/usr/share/GConf/gsettings/ibus.convert
/usr/share/applications/org.freedesktop.IBus.Setup.desktop
/usr/share/bash-completion/completions/ibus.bash
/usr/share/dbus-1/services/org.freedesktop.IBus.service
/usr/share/dbus-1/services/org.freedesktop.portal.IBus.service
/usr/share/defaults/dconf/db/ibus.d/00-upstream-settings
/usr/share/defaults/dconf/profile/ibus
/usr/share/gettext/its/ibus.its
/usr/share/gettext/its/ibus.loc
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.freedesktop.ibus.gschema.xml
/usr/share/ibus/component/dconf.xml
/usr/share/ibus/component/gtkpanel.xml
/usr/share/ibus/component/simple.xml
/usr/share/ibus/dicts/unicode-blocks.dict
/usr/share/ibus/dicts/unicode-names.dict
/usr/share/ibus/keymaps/common
/usr/share/ibus/keymaps/in
/usr/share/ibus/keymaps/jp
/usr/share/ibus/keymaps/kr
/usr/share/ibus/keymaps/modifiers
/usr/share/ibus/keymaps/us
/usr/share/ibus/setup/emojilang.py
/usr/share/ibus/setup/engineabout.py
/usr/share/ibus/setup/enginecombobox.py
/usr/share/ibus/setup/enginedialog.py
/usr/share/ibus/setup/enginetreeview.py
/usr/share/ibus/setup/i18n.py
/usr/share/ibus/setup/icon.py
/usr/share/ibus/setup/keyboardshortcut.py
/usr/share/ibus/setup/main.py
/usr/share/ibus/setup/setup.ui
/usr/share/icons/hicolor/16x16/apps/ibus-keyboard.png
/usr/share/icons/hicolor/22x22/apps/ibus-keyboard.png
/usr/share/icons/hicolor/24x24/apps/ibus-keyboard.png
/usr/share/icons/hicolor/32x32/apps/ibus-keyboard.png
/usr/share/icons/hicolor/48x48/apps/ibus-keyboard.png
/usr/share/icons/hicolor/scalable/apps/ibus-engine.svg
/usr/share/icons/hicolor/scalable/apps/ibus-keyboard.svg
/usr/share/icons/hicolor/scalable/apps/ibus-setup.svg
/usr/share/icons/hicolor/scalable/apps/ibus.svg
/usr/share/vala/vapi/ibus-1.0.deps
/usr/share/vala/vapi/ibus-1.0.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/ibus-1.0/ibus.h
/usr/include/ibus-1.0/ibusaccelgroup.h
/usr/include/ibus-1.0/ibusattribute.h
/usr/include/ibus-1.0/ibusattrlist.h
/usr/include/ibus-1.0/ibusbus.h
/usr/include/ibus-1.0/ibuscomponent.h
/usr/include/ibus-1.0/ibusconfig.h
/usr/include/ibus-1.0/ibusconfigservice.h
/usr/include/ibus-1.0/ibusdebug.h
/usr/include/ibus-1.0/ibusemoji.h
/usr/include/ibus-1.0/ibusengine.h
/usr/include/ibus-1.0/ibusenginedesc.h
/usr/include/ibus-1.0/ibusenginesimple.h
/usr/include/ibus-1.0/ibusenumtypes.h
/usr/include/ibus-1.0/ibuserror.h
/usr/include/ibus-1.0/ibusfactory.h
/usr/include/ibus-1.0/ibushotkey.h
/usr/include/ibus-1.0/ibusinputcontext.h
/usr/include/ibus-1.0/ibuskeymap.h
/usr/include/ibus-1.0/ibuskeys.h
/usr/include/ibus-1.0/ibuskeysyms-compat.h
/usr/include/ibus-1.0/ibuskeysyms.h
/usr/include/ibus-1.0/ibuslookuptable.h
/usr/include/ibus-1.0/ibusobject.h
/usr/include/ibus-1.0/ibusobservedpath.h
/usr/include/ibus-1.0/ibuspanelservice.h
/usr/include/ibus-1.0/ibusproperty.h
/usr/include/ibus-1.0/ibusproplist.h
/usr/include/ibus-1.0/ibusproxy.h
/usr/include/ibus-1.0/ibusregistry.h
/usr/include/ibus-1.0/ibusserializable.h
/usr/include/ibus-1.0/ibusservice.h
/usr/include/ibus-1.0/ibusshare.h
/usr/include/ibus-1.0/ibustext.h
/usr/include/ibus-1.0/ibustypes.h
/usr/include/ibus-1.0/ibusunicode.h
/usr/include/ibus-1.0/ibusutil.h
/usr/include/ibus-1.0/ibusversion.h
/usr/include/ibus-1.0/ibusxevent.h
/usr/include/ibus-1.0/ibusxml.h
/usr/lib64/libibus-1.0.so
/usr/lib64/pkgconfig/ibus-1.0.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/ibus/IBusAttrList.html
/usr/share/gtk-doc/html/ibus/IBusAttribute.html
/usr/share/gtk-doc/html/ibus/IBusBus.html
/usr/share/gtk-doc/html/ibus/IBusComponent.html
/usr/share/gtk-doc/html/ibus/IBusConfig.html
/usr/share/gtk-doc/html/ibus/IBusConfigService.html
/usr/share/gtk-doc/html/ibus/IBusEngine.html
/usr/share/gtk-doc/html/ibus/IBusEngineDesc.html
/usr/share/gtk-doc/html/ibus/IBusEngineSimple.html
/usr/share/gtk-doc/html/ibus/IBusFactory.html
/usr/share/gtk-doc/html/ibus/IBusHotkeyProfile.html
/usr/share/gtk-doc/html/ibus/IBusInputContext.html
/usr/share/gtk-doc/html/ibus/IBusKeymap.html
/usr/share/gtk-doc/html/ibus/IBusLookupTable.html
/usr/share/gtk-doc/html/ibus/IBusObject.html
/usr/share/gtk-doc/html/ibus/IBusObservedPath.html
/usr/share/gtk-doc/html/ibus/IBusPanelService.html
/usr/share/gtk-doc/html/ibus/IBusPropList.html
/usr/share/gtk-doc/html/ibus/IBusProperty.html
/usr/share/gtk-doc/html/ibus/IBusProxy.html
/usr/share/gtk-doc/html/ibus/IBusRegistry.html
/usr/share/gtk-doc/html/ibus/IBusSerializable.html
/usr/share/gtk-doc/html/ibus/IBusService.html
/usr/share/gtk-doc/html/ibus/IBusText.html
/usr/share/gtk-doc/html/ibus/annotation-glossary.html
/usr/share/gtk-doc/html/ibus/api-index-full.html
/usr/share/gtk-doc/html/ibus/ch01.html
/usr/share/gtk-doc/html/ibus/ch02.html
/usr/share/gtk-doc/html/ibus/ch03.html
/usr/share/gtk-doc/html/ibus/ch04.html
/usr/share/gtk-doc/html/ibus/ch05.html
/usr/share/gtk-doc/html/ibus/ch06.html
/usr/share/gtk-doc/html/ibus/home.png
/usr/share/gtk-doc/html/ibus/ibus-IBusKeysyms.html
/usr/share/gtk-doc/html/ibus/ibus-ibusdebug.html
/usr/share/gtk-doc/html/ibus/ibus-ibuserror.html
/usr/share/gtk-doc/html/ibus/ibus-ibuskeys.html
/usr/share/gtk-doc/html/ibus/ibus-ibuskeysyms-compat.html
/usr/share/gtk-doc/html/ibus/ibus-ibusshare.html
/usr/share/gtk-doc/html/ibus/ibus-ibustypes.html
/usr/share/gtk-doc/html/ibus/ibus-ibusutil.html
/usr/share/gtk-doc/html/ibus/ibus-ibusversion.html
/usr/share/gtk-doc/html/ibus/ibus-ibusxml.html
/usr/share/gtk-doc/html/ibus/ibus.devhelp2
/usr/share/gtk-doc/html/ibus/index.html
/usr/share/gtk-doc/html/ibus/left-insensitive.png
/usr/share/gtk-doc/html/ibus/left.png
/usr/share/gtk-doc/html/ibus/right-insensitive.png
/usr/share/gtk-doc/html/ibus/right.png
/usr/share/gtk-doc/html/ibus/style.css
/usr/share/gtk-doc/html/ibus/up-insensitive.png
/usr/share/gtk-doc/html/ibus/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/gtk-2.0/2.10.0/immodules/im-ibus.so
/usr/lib64/gtk-3.0/3.0.0/immodules/im-ibus.so
/usr/lib64/libibus-1.0.so.5
/usr/lib64/libibus-1.0.so.5.0.524

%files libexec
%defattr(-,root,root,-)
/usr/libexec/ibus-dconf
/usr/libexec/ibus-engine-simple
/usr/libexec/ibus-portal
/usr/libexec/ibus-ui-gtk3
/usr/libexec/ibus-wayland
/usr/libexec/ibus-x11

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ibus/8f3995295bed2abde3107e544c985096cb9c745a
/usr/share/package-licenses/ibus/caeb68c46fa36651acf592771d09de7937926bb3

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ibus-daemon.1.gz
/usr/share/man/man1/ibus-setup.1.gz
/usr/share/man/man1/ibus.1.gz
/usr/share/man/man5/00-upstream-settings.5.gz
/usr/share/man/man5/ibus.5.gz

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files locales -f ibus10.lang
%defattr(-,root,root,-)

